import Alignment from "./Alignment.jsx";
import BaseAlignment from "./components/BaseAlignment.jsx";
import BaseSVGAlignment from "./components/BaseSVGAlignment.jsx";
import SiteAxis from "./components/SiteAxis.jsx";
import SitePlotAxis from "./components/SitePlotAxis.jsx";
import SequenceAxis from "./components/SequenceAxis.jsx";
import fastaParser from "./helpers/fasta";
import computeLabelWidth from "./helpers/computeLabelWidth";
import ScrollBroadcaster from "./helpers/ScrollBroadcaster";
import colors from "./helpers/colors";

module.exports = Alignment;
module.exports.Alignment = Alignment;
module.exports.BaseAlignment = BaseAlignment;
module.exports.BaseSVGAlignment = BaseSVGAlignment;
module.exports.SiteAxis = SiteAxis;
module.exports.SitePlotAxis = SitePlotAxis;
module.exports.SequenceAxis = SequenceAxis;
module.exports.fastaParser = fastaParser;
module.exports.computeLabelWidth = computeLabelWidth;
module.exports.ScrollBroadcaster = ScrollBroadcaster;
module.exports.colors = colors;
